### PR TITLE
ServicesController - all related issues

### LINKED ISSUE #68: ServicesController - All related issues
Index/Details/Delete view:
- [ ] Display Clinic associated with Service

Create view:
- [ ] Display dropdown list for Clinics

Edit view
- [ ] Display Clinic associated with Service

### PR DESCRIPTION
**Pull request by TungKimProgrammer**
Index/Details/Delete view:
- [x] Display Clinic associated with Service

Create view:
- [x] Display dropdown list for Clinics

Edit view
- [x] Display dropdown list for Clinics with selected item is current Clinic

In general:
- [x] Added more buttons to views to help users navigate more conveniently
- [x] Added styling to buttons
- [x] Added TempData["Message"] to show status of actions
- [x] All CRUD functionalities work properly

This branch includes the deletion of the Migration folder. Might need to delete project localDB and run EasyAppointmentManager.sql to add Test Data

Closes #68 

Please merge after review!

### CODE REVIEW

**Review by crex424 — COMMENTED** [review]
Currently the issue I am running into is that the Service Index is not populated with data.

**Review by crex424 — APPROVED** [review]
It works on my side, go ahead and merge

**Comment by crex424** [comment]
@TungKimProgrammer Seems some updates need to be made to the Test Data. When I use it, service stays empty. Seems something is going wrong with it due to the changes. Maybe is because of the ClinicId needing to be added to the INSERT.

**Comment by TungKimProgrammer** [comment]
I updated the file with ClinicId in the Insert query. Or you can use the commented-out code to inject ClinicId to existing data

**Pull request merged**
